import React from "react";

export const Card = ({ children, className="" }) => <div className={"card "+className}>{children}</div>;
export const CardContent = ({ children, className="" }) => <div className={className}>{children}</div>;
export const Button = ({ children, className="", ...p }) => <button className={"button "+className} {...p}>{children}</button>;
export const Input = (props) => <input className="input" {...props}/>;
export const Textarea = (props) => <textarea className="input" {...props}/>;
export const Tabs = ({ children }) => <div>{children}</div>;
export const TabsList = ({ children }) => <div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{children}</div>;
export const TabsTrigger = ({ children, value }) => <button className="button" style={{background:'#e2e8f0', color:'#0f172a'}}>{children}</button>;
export const TabsContent = ({ children }) => <div>{children}</div>;
export const Badge = ({ children }) => <span className="badge">{children}</span>;
export const Tooltip = ({ children }) => <span>{children}</span>;
export const TooltipContent = ({ children }) => <div>{children}</div>;
export const TooltipProvider = ({ children }) => <>{children}</>;
export const Progress = ({ value=0, className="" }) => <div className={"progress "+className}><i style={{width: Math.max(2, Math.min(100, value)) + "%"}}/></div>;
export const Switch = ({ checked, onCheckedChange }) => <input type="checkbox" checked={checked} onChange={e=>onCheckedChange && onCheckedChange(e.target.checked)} />;
export const Alert = ({ children }) => <div style={{padding:8, borderRadius:8, background:'#f8fafc'}}>{children}</div>;
export const AlertTitle = ({ children }) => <div style={{fontWeight:700}}>{children}</div>;
export const AlertDescription = ({ children }) => <div className="small">{children}</div>;
export const Lightbulb = () => <span>💡</span>;
export const Info = () => <span>ⓘ</span>;
export const Gauge = () => <span>⏱️</span>;
export const Rocket = () => <span>🚀</span>;
export const BarChart3 = () => <span>📊</span>;
export const CalendarClock = () => <span>🗓️</span>;
export const BellRing = () => <span>🔔</span>;
export const PlaySquare = () => <span>▶️</span>;
export const FolderTree = () => <span>📁</span>;
export const UsersRound = () => <span>👥</span>;
export const ShieldCheck = () => <span>🛡️</span>;
export const Settings2 = () => <span>⚙️</span>;
export const CloudUpload = () => <span>☁️</span>;
export const ScanText = () => <span>🔍</span>;
export const ListChecks = () => <span>✅</span>;
export const Sparkles = () => <span>✨</span>;
export const Light = () => <span>🌤️</span>;